name:
  CI - Build Backend


on:
  pull_request:
    branches:
      - master
    paths:
      - backend/**

jobs:
  build:
    runs-on:
      ubuntu-latest
    services:
      postgres:
        image: postgres:16.2
        env:
          POSTGRES_USER: atom
          POSTGRES_PASSWORD: Password
          POSTGRES_DB: customers
        ports:
            - 5332:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5